login: &login
  adapter: postgresql
  username: mhan
  host: localhost
  port: 5432

development:
  <<: *login
  database: SnapNSave_dev

test: &test
  <<: *login
  database: SnapNSave_test

production:
  <<: *login
  database: SnapNSave_production
